steps:

- id: 'build ae-randomizer'
  name: 'gcr.io/cloud-builders/docker'
  args: [
    'build', 
    '--tag=gcr.io/$PROJECT_ID/frank-image', 
    '--tag=ae-randomizer',
    'ae-randomizer/.']

- id: 'compose up'
  name: 'gcr.io/$PROJECT_ID/docker-compose:latest'
  entrypoint: '/bin/bash'
  args:
  - '-c'
  - |
    docker-compose up -d 
  env:
  - 'PROJECT_ID=$PROJECT_ID'
  waitFor: ['build ae-randomizer']

- id: 'integration tests'
  name: 'gcr.io/$PROJECT_ID/docker-compose:latest'
  entrypoint: '/bin/bash'
  args: 
    - '-c'
    - |
      ### -r = retries; -i = interval; -k = keyword to search for ###
      chmod +x ./test/test-connectivity.sh && ./test/test-connectivity.sh -r 20 -i 3 -u http://ae-randomizer:5000
  waitFor: ['compose up']